name:                primes
version:             0.1.0.0
github:              "slfotg/primes-hs"
license:             BSD3
author:              "Sam Foster"
maintainer:          "slfotg@gmail.com"
copyright:           "2022 Sam Foster"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/slfotg/primes-hs#readme>

dependencies:
  - base >= 4.7 && < 5
  - vector >= 0.12.3.1
  - bitvec >= 1.1.2
  - data-memocombinators >= 0.5.1

library:
  source-dirs: src

tests:
  primes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - primes
